language: java
addons:
    sonarcloud:
        organization: steinarb-github
        token: $SONAR_TOKEN
script:
    - mvn -B -Dorg.slf4j.simpleLogger.defaultLogLevel=warn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar coveralls:report

deploy:
    provider: script
    script: bash scripts/deploy.sh
    skip_cleanup: true
