* Oldalbum

This is an application to display old image archives in a more attractive and modern way.

I have some old albums from the 90ies that I occasionally would like to link to.  Since the images lack [[https://ogp.me][Open Graph]] or [[https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/abouts-cards][twitter card]] tags, linking to the images from social media doesn't look to hot.

I first thought about changing the perl script that generates the albums, to add a wrapper to the main jpeg, with the OpenGraph headers.

But then the thought struck me: I can just leave the old JPEGs where they are and create a completely separate webapp that provides a navigation and metadata framework and just uses an <img> tag to display the images from the location where they are today.

And this is the webapp, called "oldalbum", because it is more a way to display existing old albums than yet another album application

** Status

[[https://travis-ci.org/steinarb/oldalbum][file:https://travis-ci.org/steinarb/oldalbum.svg?branch=master]] [[https://sonarcloud.io/dashboard?id=no.priv.bang.oldalbum%3Aoldalbum][file:https://sonarcloud.io/api/project_badges/measure?project=no.priv.bang.oldalbum%3Aoldalbum&metric=alert_status#.svg]] [[https://maven-badges.herokuapp.com/maven-central/no.priv.bang.oldalbum/oldalbum][file:https://maven-badges.herokuapp.com/maven-central/no.priv.bang.oldalbum/oldalbum/badge.svg]] [[https://www.javadoc.io/doc/no.priv.bang.oldalbum/oldalbum][file:https://www.javadoc.io/badge/no.priv.bang.oldalbum/oldalbum.svg]]

*** SonarCloud

[[https://sonarcloud.io/dashboard/index/no.priv.bang.oldalbum%3Aoldalbum][file:https://sonarcloud.io/api/project_badges/measure?project=no.priv.bang.oldalbum%3Aoldalbum&metric=ncloc#.svg]] [[https://sonarcloud.io/dashboard/index/no.priv.bang.oldalbum%3Aoldalbum][file:https://sonarcloud.io/api/project_badges/measure?project=no.priv.bang.oldalbum%3Aoldalbum&metric=bugs#.svg]] [[https://sonarcloud.io/dashboard/index/no.priv.bang.oldalbum%3Aoldalbum][file:https://sonarcloud.io/api/project_badges/measure?project=no.priv.bang.oldalbum%3Aoldalbum&metric=vulnerabilities#.svg]] [[https://sonarcloud.io/dashboard/index/no.priv.bang.oldalbum%3Aoldalbum][file:https://sonarcloud.io/api/project_badges/measure?project=no.priv.bang.oldalbum%3Aoldalbum&metric=code_smells#.svg]] [[https://sonarcloud.io/dashboard/index/no.priv.bang.oldalbum%3Aoldalbum][file:https://sonarcloud.io/api/project_badges/measure?project=no.priv.bang.oldalbum%3Aoldalbum&metric=coverage#.svg]]

** Installation

*** Installation with test database
 Procedure:
  1. Download and install apache karaf
  2. From the karaf console, give the following commands:
     #+BEGIN_EXAMPLE
       feature:repo-add mvn:no.priv.bang.oldalbum/oldalbum/LATEST/xml/features
       feature:install oldalbum-with-derby
     #+END_EXAMPLE

*** Installation with production database
 Procedure:
  1. Download and install apache karaf
  2. From the karaf console, give the following commands:
     #+BEGIN_EXAMPLE
       feature:repo-add mvn:no.priv.bang.authservice/authservice/LATEST/xml/features
       feature:install user-admin-with-productiondb
       feature:repo-add mvn:no.priv.bang.oldalbum/oldalbum/LATEST/xml/features
       feature:install oldalbum-with-postgresql-and-provided-authservice
     #+END_EXAMPLE

** License

This software is licensed under Apache Public License v 2.0.

See the LICENSE file for the full details.
