* Oldalbum

If you have some old image archives from the web's baby years in the 90-ies and would like to link to the images from social media and have the linked images show up nicely, then this is the application you have waited for.

The application can be run in two ways:
 1. With a PostgreSQL database
 2. With an in-memory derby database that is provisioned from a file loaded from an URL (you need a web server that can serve the file)

The application doesn't store the images.  You need to let the original image archive to keep running.  The application just points into the old image archive and serve up the images with open graph and twitter card meta tags added.

The images are served up in a bootstrap styled, responsive layout, and should appear nicely on both mobile devices and larger screens.

** The reason this application exists
 The idea for the application comes from that I have some old albums from the 90ies that I occasionally would like to link to.  Since the images lack [[https://ogp.me][Open Graph]] or [[https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/abouts-cards][twitter card]] tags, linking to the images from social media doesn't look to hot.

 I first thought about changing the perl script that generates the albums, to add a wrapper to the main jpeg, with the OpenGraph headers.

 But then the thought struck me: I could just leave the old JPEGs where they are and create a completely separate webapp that provides a navigation and metadata framework and just uses an <img> tag to display the images from the location where they are today.

 And this is the webapp, called "oldalbum", because it is more a way to display existing old albums than yet another album application

** Status

[[https://travis-ci.org/steinarb/oldalbum][file:https://travis-ci.org/steinarb/oldalbum.svg?branch=master]] [[https://sonarcloud.io/dashboard?id=no.priv.bang.oldalbum%3Aoldalbum][file:https://sonarcloud.io/api/project_badges/measure?project=no.priv.bang.oldalbum%3Aoldalbum&metric=alert_status#.svg]] [[https://maven-badges.herokuapp.com/maven-central/no.priv.bang.oldalbum/oldalbum][file:https://maven-badges.herokuapp.com/maven-central/no.priv.bang.oldalbum/oldalbum/badge.svg]] [[https://www.javadoc.io/doc/no.priv.bang.oldalbum/oldalbum][file:https://www.javadoc.io/badge/no.priv.bang.oldalbum/oldalbum.svg]]

*** SonarCloud

[[https://sonarcloud.io/dashboard/index/no.priv.bang.oldalbum%3Aoldalbum][file:https://sonarcloud.io/api/project_badges/measure?project=no.priv.bang.oldalbum%3Aoldalbum&metric=ncloc#.svg]] [[https://sonarcloud.io/dashboard/index/no.priv.bang.oldalbum%3Aoldalbum][file:https://sonarcloud.io/api/project_badges/measure?project=no.priv.bang.oldalbum%3Aoldalbum&metric=bugs#.svg]] [[https://sonarcloud.io/dashboard/index/no.priv.bang.oldalbum%3Aoldalbum][file:https://sonarcloud.io/api/project_badges/measure?project=no.priv.bang.oldalbum%3Aoldalbum&metric=vulnerabilities#.svg]] [[https://sonarcloud.io/dashboard/index/no.priv.bang.oldalbum%3Aoldalbum][file:https://sonarcloud.io/api/project_badges/measure?project=no.priv.bang.oldalbum%3Aoldalbum&metric=code_smells#.svg]] [[https://sonarcloud.io/dashboard/index/no.priv.bang.oldalbum%3Aoldalbum][file:https://sonarcloud.io/api/project_badges/measure?project=no.priv.bang.oldalbum%3Aoldalbum&metric=coverage#.svg]]

*** Release history

| Date                   | Version | Description                                                                          |
|------------------------+---------+--------------------------------------------------------------------------------------|
| <2020-09-23 Wed 23:05> |   1.4.0 | Added swipe between pictures, added environment variables for docker image config    |
| <2020-09-13 Sun 23:11> |   1.3.0 | More large display improvements, webcrawler friendly title/description, docker image |
| <2020-09-01 Tue 22:03> |   1.2.0 | Improved layout on large display. REST endpoint for dumping database                 |
| <2020-08-26 Wed 23:41> |   1.1.0 | Make page preview work in twitter, show prev/next arrows better on large displays    |
| <2020-08-23 Sun 00:29> |   1.0.0 | First release                                                                        |

** Installation

*** Installation with test database
 Procedure:
  1. Download and install apache karaf
  2. From the karaf console, give the following commands:
     #+BEGIN_EXAMPLE
       feature:repo-add mvn:no.priv.bang.oldalbum/oldalbum/LATEST/xml/features
       feature:install oldalbum-with-derby
     #+END_EXAMPLE

*** Installation with production database
 Procedure:
  1. Download and install apache karaf
  2. Create PosgreSQL user karaf, and give "karaf" (without the quotes) as the password (or pick a different password, and change the database password in the karaf config file =etc/org.ops4j.datasource-oldalbum-production.cfg=, note1: this is =etc/= inside karaf note2: the file is created after oldalbum installation, and you will have to restart karaf after changing the config file):
     #+begin_example
       /usr/bin/sudo -u postgres createuser karaf --pwprompt
     #+end_example
  3. Create a blank PostgreSQL database with user karaf as the owner
     #+begin_example
       /usr/bin/sudo -u postgres createdb -O karaf oldalbum
     #+end_example
  4. From the karaf console, give the following commands:
     #+BEGIN_EXAMPLE
       feature:repo-add mvn:no.priv.bang.authservice/authservice/LATEST/xml/features
       feature:install user-admin-with-productiondb
       feature:repo-add mvn:no.priv.bang.oldalbum/oldalbum/LATEST/xml/features
       feature:install oldalbum-with-postgresql-and-provided-authservice
     #+END_EXAMPLE

*** Installation with in-memory database initialized from URL

Procedure:
 1. Set the environment variable DATABASE_CONTENT_URL pointing to the raw content of a [[https://gist.github.com/steinarb/dba5f579774d04e69f3073d029622027][github gist containing a liquibase changeset setting up just an empty root album]] :
    #+begin_example
      export DATABASE_CONTENT_URL=https://git.io/JUnF4
    #+end_example
 2. Start karaf from the shell where you've set the DATABASE_CONTENT_URL environment variable
 3. Install the oldalbum application :
    #+begin_example
      feature:repo-add mvn:no.priv.bang.oldalbum/oldalbum/LATEST/xml/features
      feature:install oldalbum-with-memory-db-with-url-init
    #+end_example
 4. Visit http://localhost:8181/oldalbum in a web browser:
    1. Log in with username "admin" (without the quotes) and password "admin" (also without the quotes)
    2. Add the albums and images you want to display
 5. When you're happy with the album contents, download http://localhost:8181/oldalbum/api/dumpsql and put the results in a place that can be reached with a HTTP URL from where you start your production karaf instance, e.g. as a github gist
 6. Set the environment variable DATABASE_CONTENT_URL to the raw content of your github gist in the shell where you'll start the karaf hosting your production oldalbum instance

*** Installation using docker image

Procedure:
 1. Pull the latest version of the image from docker hub
    #+begin_example
      docker pull steinarb/oldalbum:latest
    #+end_example
    (/Note/! The image provisions the latest released version of oldalbum from maven central on startup, so there is no need to get a new version of the image to get a new oldalbum release. A stop and start of the image will be sufficient)
 2. Start the docker image with a minimal database that only contains the top album
    #+begin_example
      docker run -p 8101:8101 -p 8181:8181  -e "DATABASE_CONTENT_URL=https://git.io/JUnF4" -d steinarb/oldalbum:latest
    #+end_example
 3. Visit http://localhost:8181/oldalbum in a web browser:
    1. Log in with username "admin" (without the quotes) and password "admin" (also without the quotes)
    2. Add the albums and images you want to display
 4. When you're happy with the album contents, download http://localhost:8181/oldalbum/api/dumpsql and put the results in a place that can be reached with a HTTP URL from where you start your production karaf instance, e.g. as a github gist
 5. Stop the image and restart it, this time with a DATABASE_CONTENT_URL pointing to a web server serving up the dumped file (as e.g. with this github gist):
    #+begin_example
      docker run -p 8101:8101 -p 8181:8181  -e "DATABASE_CONTENT_URL=https://gist.githubusercontent.com/steinarb/8a1de4e37f82d4d5eeb97778b0c8d459/raw/6cddf18f12e98d704e85af6264d81867f68a097c/dumproutes.sql" -d steinarb/oldalbum:latest
    #+end_example

**** Set admin user username and password when using docker

If you want to change the username and/or password of the admin user, it can be done by setting the environment variables USERNAME and PASSWORD, e.g. like so:
#+begin_example
  docker run -p 8101:8101 -p 8181:8181  -e "DATABASE_CONTENT_URL=https://git.io/JUnF4" -e "USERNAME=album" -e "PASSWORD=zekret" -d steinarb/oldalbum:latest
#+end_example


**** Read-only installation using docker

If you want your album to be read-only, it's possible to disable the login and the edit functionality by setting the environmentvariable ALLOW_MODIFY, e.g. like so:
#+begin_example
  docker run -p 8101:8101 -p 8181:8181  -e "ALLOW_MODIFY=false" -e "DATABASE_CONTENT_URL=https://gist.githubusercontent.com/steinarb/8a1de4e37f82d4d5eeb97778b0c8d459/raw/6cddf18f12e98d704e85af6264d81867f68a097c/dumproutes.sql" -d steinarb/oldalbum:latest
#+end_example

** License

This software is licensed under Apache Public License v 2.0.

See the LICENSE file for the full details.
