FROM apache/karaf:4.2.9
COPY org.ops4j.pax.url.mvn.cfg /opt/apache-karaf/etc
COPY org.apache.karaf.features.cfg /opt/apache-karaf/etc
COPY org.ops4j.datasource-oldalbum-urlinit.cfg /opt/apache-karaf/etc
COPY org.ops4j.datasource-authservice-test.cfg /opt/apache-karaf/etc
